### ISSUE TITLE
The zoom buttons don't work

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#14]
**Describe the bug**
The zoom buttons don't work as expected.

**To Reproduce**
Just click on the zoom buttons.

**Expected behavior**
The zoom buttons should zoom in and out as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/1699357/44880205-161aaf00-acac-11e8-8929-e72cd22df695.png)

**Comment by gioboa** [comment]
Hi @manekinekko,
I check the issue and the fix is really simple.
In `sketch-container.component.ts` there is a typo.
If you change @ViewChild('canvasRef') in @ViewChild('canvas') the zoom works good.
Now there are other 2 issues:
- the zoom is on the top left corner
- the x scrollbar does not appear even if it is necessary

**Comment by manekinekko** [comment]
That's awesome! thanks for investigating this.
Would you mind creating an issue with a detailed description so we can look into this? 🙏🏻

**Comment by gioboa** [comment]
@manekinekko I created the other two issues so I think you can close this one because it's fixed.
