### ISSUE TITLE
Replace Monaco editor with a simple code bloc

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#149]
**Is your feature request related to a problem? Please describe.**
The issue is this one https://github.com/xlayers/xlayers/issues/105

**Describe the solution you'd like**
We can entirely remove the monaco editor and use simple code blocs to show the generated code. 

**Additional context**
This can be similar to what the Material team is using...
![image](https://user-images.githubusercontent.com/1699357/50848748-56362080-1375-11e9-9ffb-9957a6c189ff.png)

**Comment by Shikanime** [comment]
I will look at it

**Comment by Shikanime** [comment]
I tried some alternative like Prism but it doesn't looked great on xlayers. And ngx-highlightjs (because the Angular Material seem to use it as well) but i kinda having trouble with it and I not really sure of why it doesn't work without weird tricks 😢

**Comment by sumitparakh** [comment]
Hi @Shikanime . May I try? Can you tell what problems are you facing with this integration? What exactly doesn't work in ngx-highlight without weird tricks?

**Comment by manekinekko** [comment]
@Shikanime can you give Summit more details?

**Comment by Shikanime** [comment]
Hi @sumitparakh,
So I followed the documentation and Stackblitz demo of https://github.com/murhafsousli/ngx-highlightjs but it doesn't work.
It seems that languages are undefined if I import the `HighlightModule` from `AppModule` and `CodeEditor`.

**Comment by sumitparakh** [comment]
Thanks @Shikanime . I'll try tomorrow evening.

**Comment by sumitparakh** [comment]
Hi @Shikanime . I'm not quite sure why you are getting "No languages were registered!" error because i just installed highlightjs (  `npm install -S ngx-highlightjs highlight.js` ), Inserted HighlightModule in code editor module and i didn't get any error. 

Here is my version of code-editor.module.ts :-  https://gist.github.com/sumitparakh/d52fed371afed643ad78eb7fb6a56c09

I'm trying to understand why you got this error.

You experimented with both prism and hightlightjs . Can you confirm if prism was already installed while you were working with highlightjs? If yes, then may be there must be some conflicting issues between their modules and uninstalling prism might help fix that.

**Comment by Shikanime** [comment]
Hi @sumitparakh . That is weird, i did the same thing except the fact that i removed all Monaco related code and package.

**Comment by Shikanime** [comment]
On your side did you try to use the ```html
<pre><code [highlight]="someCode"></code></pre>
```
Because the error pop out at this moment.

**Comment by sumitparakh** [comment]
Hi @Shikanime , I think you missed lazy loading example  of its [stackblitz example](https://stackblitz.com/edit/ngx-highlightjs-children) ... It imports HighlightModule with languages in main app.module(AppModule) & only HighlightModule in lazy loading modue (LazyTestModule)....

I did the same in my xlayers code and it worked.
