### ISSUE TITLE
Could not load a Sketch preview "images/5dd04a87d1827ce5b0a269d480e531417eafcce4.pdf"

### ISSUE THREAD

**Issue by bitcointroy** [xlayers/xlayers#323]
**Describe the bug**
Source Sketch File from the UX/UI designer won't load on xlayers.dev

**To Reproduce**
1. Go to 'xlayers.dev'
2. Click on 'upload file from your computer'
3. Scroll down to 'sharetribe flex desktop'

**Expected behavior**
Source file uploaded into xlayers.dev so we can convert from Sketch to react code

**Screenshots**

**Sketch (please complete the following information):**
- version: web interface (v53?)

**Desktop (please complete the following information):**
 - OS: win7, macOS (both have experienced the same error)
 - Browser: chrome, safari
 - Version: latest for both

**Smartphone (please complete the following information):**
 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

**Additional context**
I couldn't upload the sketch file to github, but you can download it here: 
https://www.dropbox.com/s/unzg262038i2s4d/Sharetribe-FLEX_Desktop.sketch?dl=0

**Comment by Jefiozie** [comment]
Hi, thank you for taking your time to submit this issue. Based on the provided error I believe this issue is the same issue as described in #321, would you mind to verify this for me? The fix for this issue is already provided in the issue. 

If your are willing to contribute or always wanted to start contribute we can help you with this by guiding you through the process. If you're not interested that's fine also 😊

**Comment by bitcointroy** [comment]
That appears to be the same issue. I'll run locally and make the adjustment to the code and let you know if it works. Thanks!

**Comment by Jefiozie** [comment]
hey @bitcointroy, did you have some time to look into the issue? If you didn't worry  just checking in 😃

**Comment by Jefiozie** [comment]
This issue is fixed by #324 when we deploy a new release you should be able to work with version 56 of sketch.
