### ISSUE TITLE
Rethink xLayers's UX

### ISSUE THREAD

**Issue by manekinekko** [xlayers/xlayers#379]
**Is your feature request related to a problem? Please describe.**
- Currently, when users open the landing page at xlayers.dev, they can read about what's xlayers. 
- Next, they click on get started, and get redirected to the [upload](https://xlayers.dev/upload) page.
- After uploading a design file, they get redirected to [the preview UI](https://xlayers.dev/#/editor/preview) where they can inspect their design.
- If they want to generate code from the design, [from the code generation UI](https://xlayers.dev/#/editor/code), xlayers generates code for ALL supported framework at once!

This could be problematic when we will have a lot of supported frameworks. We need to simply this workflow.

**Describe the solution you'd like**
- On the landing page, we should allow users to choose their framework they wanna generate code for.
- When clicking on the framework, they will get redirected to the upload UI to upload their design.
- The rest of the workflow should be the same, expect...
- The code generation UI now only show the selected framework.
  - Note: we should allow users to instantly switch the selected framework (from the code generation UI).

**Comment by ayshiff** [comment]
Hi @manekinekko ! Can I start working on this ? 👍

**Comment by manekinekko** [comment]
Yes sure! Please send us your suggestions 😃

**Comment by ayshiff** [comment]
Here is my suggestions which I thought about last night.
I prefer to iterate regularly to get your feedback as quickly as possible to be more efficient and to be sure that I am going in the right direction.

## Landing Page

Currently I have two ideas about this page.

#### Idea 1

The first one is something similar to [codesanbox.io](https://codesandbox.io/?from-app=1) web app with maybe a carousel if we have a lot of frameworks to display to the user.

<p align="center">
<img width="590" alt="Capture d’écran 2020-10-23 à 11 37 25" src="https://user-images.githubusercontent.com/32459935/96988315-77550a80-1524-11eb-8e31-09cb2819f636.png">
</p>

#### Idea 2

The second one is something more usual with a simple select component.
We could add a search bar at the top of the dropdown to help the user find his framework.

<p align="center">
<img width="635" alt="Capture d’écran 2020-10-23 à 11 37 35" src="https://user-images.githubusercontent.com/32459935/96988516-baaf7900-1524-11eb-8ed8-a62ea53bb423.png">
</p>

## Code generation UI

As this page already includes a way to switch between frameworks, I was thinking about removing the frameworks tab bar and replacing it with a simple dropdown component which will be much more unobtrusive and it will not disturb the user. (And we also save space for the code editor).

<p align="center">
<img width="897" alt="Capture d’écran 2020-10-23 à 11 37 47" src="https://user-images.githubusercontent.com/32459935/96988542-c13df080-1524-11eb-876d-f630c4edac71.png">
</p>

Tell me what you think about this ideas !
I would be happy to discuss about these 👍

**Comment by anediaz** [comment]
Thank you for your suggestions !
If you don't mind, I take the liberty of giving my opinion :-)
For the **Landing Page**, I prefer the first idea, I love the carousel proposition. I think it can give freshness to the website and a modern touch.

For the **Code Generation UI**, I agree with your idea of removing some elements in order to gain some space and create a better user experience.
I also like your suggestion of a simple dropdown component, I think it's the best solution to give more space to the code editor.

Thank you for having shared your ideas!!

**Comment by Jefiozie** [comment]
Let me first thank you for creating these ideas and the effort you've put into it! 🙏🏻

About the **Landing Page**
I like the carousel idea, it will help our users to see which frameworks are supported! Would this carousel rotate automatically? Or is only changing when users use the arrows similiar to _codesandbox_? At this moment we've some general information about the usage of xLayers below the getting started button, will this still be present or do you have another idea around this?

About the **Code Generation UI**
I think using a dropdown is a good approach to get some space and have a easy way of selecting a different framework. I'm curious, what are your thoughts on something different then the dropdown? Did you make some other ideas? 

Again thanks for sharing these ideas!

**Comment by manekinekko** [comment]
Thank you so much @ayshiff these are great suggestions!

Like @anediaz and @Jefiozie, I also prefer **option 1** for the landscape. The code generation UI looks good to me as well.

**Comment by ayshiff** [comment]
Thank you for your feedback 👍
What's the **next step** ? Do we still have to iterate on the UX ?

> Let me first thank you for creating these ideas and the effort you've put into it! 🙏🏻
> 
> About the **Landing Page**
> I like the carousel idea, it will help our users to see which frameworks are supported! Would this carousel rotate automatically? Or is only changing when users use the arrows similiar to _codesandbox_? At this moment we've some general information about the usage of xLayers below the getting started button, will this still be present or do you have another idea around this?
> 
> About the **Code Generation UI**
> I think using a dropdown is a good approach to get some space and have a easy way of selecting a different framework. I'm curious, what are your thoughts on something different then the dropdown? Did you make some other ideas?
> 
> Again thanks for sharing these ideas!

I think it's better that the carousel doesn't rotate automatically (it could create some frustration for the user who wants to click on a framework that just starts rotating at that exact moment). But I'm not 100% sure, I'm just trying to put myself in the shoes of the user who is going to be on this situation.
For the general information section I think we can leave it where it is now (just below).

Regarding the Code Generation UI I had not looked for other ideas, I was waiting to hear your feedback on those before !

By the way, I don't know if it was already there but codesandbox replaced the carousel with a « More template » choice. 

<img width="1082" alt="Capture d’écran 2020-11-08 à 12 22 53" src="https://user-images.githubusercontent.com/32459935/98463668-22b8bd00-21bd-11eb-99f3-8be4fd2a0dbe.png">

In their case I imagine that the carousel was irrelevant since they have a wide variety of templates available and they don't want the user to click 40 times before they can hit the template they want.

So I imagine that arrived at a certain number of frameworks we will have to switch to an approach similar to this to match the user's expectations.

**Comment by anediaz** [comment]
Thank you!!

I agree with you, I don't think we should rotate the carousel automatically. Personally, I feel always frustrated and annoyed with this kind of components.

But maybe, we could imagine a rotation system that turns only once, and then it stops. This way, we show the user the possibility of switching framework. The automatic rotation will be triggered the first time we get to xLayer's main page, or each time we get to it (as you wish).


I agree with you, the day we'll have more than 30 ou 40 frameworks we will have to change from Carousel to another visual component. I think it won't be a problem, we'll be happy to have so many frameworks :-P 
We still have time before this day comes.

**Comment by sumitparakh** [comment]
Nice suggestions.

I was going through the website of some cloud services and could relate UI of their service page with our requirement.

https://azure.microsoft.com/en-in/services/
https://aws.amazon.com/?nc2=h_lg (Check Explore our Solutions section)

Both are showing their services categorically . 

What if we also categorize our frameworks into:- 

1. Web, 
2. Mobile
3. All 
etc.

and then toggle them accordingly? It will also help users in quickly navigating to the platform/category based frameworks. 

Let me know what do you think about it!

(Industry & Technology Category)
![image](https://user-images.githubusercontent.com/4236211/98796527-7c292200-2431-11eb-841e-6cd72d525e6f.png)

![image](https://user-images.githubusercontent.com/4236211/98796674-a7137600-2431-11eb-9f62-4f37beb1d57d.png)

**Comment by anediaz** [comment]
@sumitparakh I'll contribute to this issue, if you're ok :-)
We'll display static icons on the landing page instead of a carousel, we think is the best solution. On the one hand, because this way we won't spend too much time with carousel's implementation. On the other hand, for the moment we don't support too much Frameworks, to this displaying way responds to our need.

In the code editor, we will use a dropdown component as you suggested :-)

I hope you're OK with this.

Let me know, do you want to do the implementation of this feature, or do you want me to do it?
Thank you for your work and your propositions, it is very enriching, and we appreciate them all!!

**Comment by sumitparakh** [comment]
Hi @anediaz. Thanks for the input.. I just wanted to share my opinion..  Please go on with your development. :)

**Comment by manekinekko** [comment]
Thank you @sumitparakh ❤️

Hey @ayshiff do you have enough bandwidth to create a prototype based on @anediaz inputs?

**Comment by ayshiff** [comment]
Hey @manekinekko I should have enough bandwidth to do this.
Is @anediaz already working on this ? 
As I saw that @anediaz wanted to start working on it I prefer to ask the question 👍

**Comment by anediaz** [comment]
No go ahead 😊
I've been assigned to this issue just in case you couldn't work on it. 
Enjoy with it!

**Comment by manekinekko** [comment]
Merged in https://github.com/xlayers/xlayers/commit/c1adf5418715929d547c2132d0aeb3b2120c68bd
